M48
; DRILL file {KiCad 7.0.0-1.fc37} date Thu 02 Mar 2023 16:58:44 GMT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-02T16:58:44+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0-1.fc37
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C4.000
%
G90
G05
T1
X124.72Y-56.425
X134.72Y-56.425
T2
X104.9Y-93.965
X104.9Y-98.815
T3
X101.87Y-93.665
X101.87Y-99.115
T4
X120.639Y-73.393
T5
X102.22Y-60.0
X102.22Y-115.0
X157.22Y-60.0
X157.22Y-115.0
T0
M30
